apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 9200
    - name: transport
      port: 9300
  selector:
    app: elasticsearch