apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash
  labels:
    app: logstash
spec:
  ports:
    - name: "tcp-beats"
      port: 5044
      targetPort: 5044
    - name: "jupyter"
      port: 8888
      targetPort: 8888