apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-config
  labels:
    app: kibana
    role: master
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    elasticsearch:
      hosts: "elasticsearch.apps.kcs4-prod-ewd.k8s.boeing.com"
      username: "kibana"
      password: "W4nwkqFWyDAu14yLgfzS"