apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: elk
  name: kibana-node
  labels:
    app: kibana
    #role: data
spec:
  serviceName: "kibana"
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  setVmMaxMapCount: false
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: "kibana"
          image: sres.web.boeing.com:5000/kibana/kibana:8.6.2
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                  memory: "1Gi"
                  cpu: "250m"
              limits:
                  memory: "2Gi"
                  cpu: "1000m"
          ports:
            - name: http
              containerPort: 5601
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch.apps.kcs4-prod-ewd.k8s.boeing.com/" # or 'http://175.1.67.49:9200'
          - name: ELASTICSEARCH_USER
            value: "kibana"
          - name: ELASTICSEARCH_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: elasticsearch-pw-kibana
                key: password
          - name: CLUSTER_NAME
            value: docker-cluster
          volumeMounts:
            - name: config
              mountPath: /usr/share/kibana/config/kibana.yml
              readOnly: true
              subPath: kibana.yml
          #readinessProbe:
          #  httpGet:
          #    path: /api/status
          #    port: http
          #  initialDelaySeconds: 20
          #  timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: kibana-config
