apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-config
  labels:
    app: kibana
    role: master
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    server.publicBaseUrl: http://kibana.apps.kcs4-prod-ewd.k8s.boeing.com
    elasticsearch:
      hosts: "192.168.11.254"
      username: "kibana"
      password: "jnGHahqMFWpJkuFQ9u4k"
