apiVersion: v1
kind: Template
metadata:
  name: tutorial1-template
  annotations:
    description: "KCS Tutorial 1-2"
    iconClass: "icon-redis"
    tags: "other"
labels:
  testlabel: tutorial1
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: web-server-2
    labels:
      app: web-server-2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web-server-2
    template:
      metadata:
        labels:
          app: web-server-2
      spec:
        containers:
        - image: sres.web.boeing.com:5000/3472487/kcs-tutorial-2:0.1
          name: web-server-2
          ports:
            - containerPort: 8000
              protocol: TCP
- kind: Service
  apiVersion: v1
  metadata:
    name: web-server-service2
    labels:
      app: web-server-2
  spec:
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: web-server-2
    type: ClusterIP
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: web-server-route2
    labels:
      app: web-server-2
  spec:
    host: ${HOSTNAME}.${KCS_ENVIRONMENT}
    port:
      targetPort: 8000
    to:
      kind: Service
      name: web-server-service2
parameters:
- description: Hostname to use for the route resource
  name: HOSTNAME
  required: true
- description: KCS environment/cluster where the resources should be created
  name: KCS_ENVIRONMENT
  required: true
